### ISSUE TITLE
API function fails

### ISSUE THREAD

**Issue by huyingjie** [lazydevorg/alfred-big-huge-thesaurus#2]
I followed the instruction

> Copy the API key from the page, open Alfred and write synonyms, a space and then paste the API key. Wait a second and an item Press enter to set the API key will appear.

Then the following message appears. API function does not work.
![screen shot 2017-03-23 at 1 04 58 pm](https://cloud.githubusercontent.com/assets/4664280/24260184/86652fdc-0fc9-11e7-9926-2f8e058b0fb0.png)

**Comment by lazydevorg** [comment]
This workflow use node.js (using the great [alfy](https://github.com/sindresorhus/alfy)) as specified in the [prerequisites](https://github.com/lazydevorg/alfred-big-huge-thesaurus#prerequisites). Unfortunately you need to install node.js on your machine in order to use it.
I don't know if it's easy to implement it using the Apple javascript engine but I'll create an issue about this and I check as soon as I can. Thank you for the feedback,
